version: '3'

services:
  
  spring-restapi:
    image: maven
    volumes:
    - ".:/data"
    working_dir: "/data"
    ports:
    - "8080:8080"
    command: bash -c "mvn clean && mvn install && java -jar target/restapi-0.0.1-SNAPSHOT.jar"
    container_name: spring-restapi





